[package]
name = "splines"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Dimitri Sabadie <dimitri.sabadie@gmail.com>"]
description = "Spline interpolation made easy"
keywords = ["spline", "interpolation"]
categories = ["science"]
homepage = "https://github.com/phaazon/spline"
repository = "https://github.com/phaazon/spline"
documentation = "https://docs.rs/spline"
readme = "README.md"

[badges]
travis-ci = { repository = "phaazon/spline", branch = "master" }
is-it-maintained-issue-resolution = { repository = "phaazon/spline" }
is-it-maintained-open-issues = { repository = "phaazon/spline" }
maintenance = { status = "actively-developed" }

[dependencies]
